add a dialog to choose active or standby position for radio frequency
LK8000/LK8000 pull request #1536
Opened 2021-02-10 21:02 UTC by AlphaLima

![image](https://user-images.githubusercontent.com/1188401/107571784-a71b4180-6beb-11eb-9363-ea6f94fd4553.png)

2021-02-11 22:12 UTC, brunotl requested changes
android target don't build

2021-03-31 20:45 UTC, brunotl commented on Common/Source/Calc/Radio.cpp
> +		return((TCHAR*)ACTIVE_SYMBOL_UTF8) ;
invalid cast

2021-03-31 20:45 UTC, brunotl commented on Common/Source/Calc/Radio.cpp
> +		return((TCHAR*)ACTIVE_SYMBOL);
invalid cast

2021-03-31 20:45 UTC, brunotl commented on Common/Source/Calc/Radio.cpp
> +		return((TCHAR*)STANDBY_SYMBOL_UTF8) ;
invalid cast

2021-03-31 20:45 UTC, brunotl commented on Common/Source/Calc/Radio.cpp
> +		return((TCHAR*)STANDBY_SYMBOL);
invalid cast

2021-03-31 20:45 UTC, brunotl commented on Common/Source/Dialogs/dlgAirspaceDetails.cpp
> +          wClose->SetWidth(IBLSCALE(80));
why not in xml template ?

2021-03-31 20:45 UTC, brunotl commented on Common/Source/Dialogs/dlgAirspaceDetails.cpp
> +        wFreq->SetWidth(IBLSCALE(75));
why not in xml template ?

2021-03-31 20:45 UTC, brunotl commented on Common/Source/Dialogs/dlgAirspaceDetails.cpp
> +        wSeqFreq->SetWidth(IBLSCALE(75));
why not in xml template ?

2021-03-31 20:45 UTC, brunotl commented on Common/Source/Dialogs/dlgRadioPriSecSel.cpp
> +    wpnewActive->SetCaption((TCHAR*)GetActiveStationSymbol(Appearance.UTF8Pictorials));
useless cast to TCHAR*

2021-03-31 20:45 UTC, brunotl commented on Common/Source/resource.h
> +#define IDR_XML_RADIOPRISECSEL      704
missing end of file CR

2021-04-01 12:52 UTC, AlphaLima commented on Common/Source/Calc/Radio.cpp
> +		return((TCHAR*)ACTIVE_SYMBOL_UTF8) ;
fixed!

2021-04-01 12:52 UTC, AlphaLima commented on Common/Source/Calc/Radio.cpp
> +		return((TCHAR*)ACTIVE_SYMBOL);
fixed!

2021-04-01 12:52 UTC, AlphaLima commented on Common/Source/Calc/Radio.cpp
> +		return((TCHAR*)STANDBY_SYMBOL_UTF8) ;
fixed!

2021-04-01 12:52 UTC, AlphaLima commented on Common/Source/Dialogs/dlgAirspaceDetails.cpp
> +          wClose->SetWidth(IBLSCALE(80));
fixed!

2021-04-01 12:52 UTC, AlphaLima commented on Common/Source/Dialogs/dlgAirspaceDetails.cpp
> +        wFreq->SetWidth(IBLSCALE(75));
fixed!

2021-04-01 12:53 UTC, AlphaLima commented on Common/Source/Dialogs/dlgRadioPriSecSel.cpp
> +    wpnewActive->SetCaption((TCHAR*)GetActiveStationSymbol(Appearance.UTF8Pictorials));
fixed!

2021-04-01 12:53 UTC, AlphaLima commented on Common/Source/resource.h
> +#define IDR_XML_RADIOPRISECSEL      704
fixed!

2021-04-01 16:38 UTC, AlphaLima commented on Common/Source/Dialogs/dlgWayPointDetails.cpp
> +        const auto hOldPen = Surface.SelectObject(LKPen_Black_N2);
done

2021-04-01 16:38 UTC, AlphaLima commented on Common/Source/Calc/Radio.cpp
> +*len =0;
done and null pointer check

2021-04-01 16:39 UTC, AlphaLima commented on Common/Source/Dialogs/dlgAirspaceDetails.cpp
> +        wSeqFreq->SetWidth(IBLSCALE(75));
done

2021-04-01 18:38 UTC, merged